export const Timezone = {
  "-12:00": "Etc/GMT+12",
  "-11:00": "Etc/GMT+11",
  "-10:00": "Hawaii",
  "-09:00": "Etc/GMT+9",
  "-08:00": "Pacific Time (US & Canada)",
  "-07:00": "Mountain Time (US & Canada)",
  "-06:00": "Central America, Guadalajara, Mexico City, Monterrey",
  "-05:00": "Bogota, Lima, Quito, Rio Branco, Eastern Time (US & Canada)",
  "-04:30": "Caracas",
  "-04:00": "Asuncion, Atlantic Time (Canada), Georgetown, La Paz, Manaus, San Juan",
  "-03:00": "Brasilia, Cayenne, Fortaleza, City of Buenos Aires, Greenland, Montevideo, Santiago",
  "-02:00": "Etc/GMT+2",
  "-01:00": "Cabo Verde Is.",
  "+00:00": "Casablanca, Dublin, Edinburgh, Lisbon, London, Monrovia, Reykjavik",
  "+01:00": "Amsterdam, Belgrade, Berlin, Bern, Bratislava, Brussels, Budapest, Copenhagen, Ljubljana, Madrid, Paris, Prague, Rome, Sarajevo, Skopje, Stockholm, Vienna, Warsaw, Windhoek, Zagreb, West Central Africa",
  "+02:00": "Amman, Athens, Beirut, Bucharest, Cairo, Damascus, E. Europe, Harare, Helsinki, Istanbul, Jerusalem, Kyiv, Pretoria, Riga, Sofia, Tallinn, Vilnius",
  "+03:00": "Baghdad, Kuwait, Minsk, Moscow, Nairobi, Riyadh, St. Petersburg",
  "+03:30": "Tehran",
  "+04:00": "Abu Dhabi, Baku, Muscat, Port Louis, Tbilisi, Yerevan",
  "+04:30": "Kabul",
  "+05:00": "Ashgabat, Islamabad, Karachi, Tashkent",
  "+05:30": "Chennai, Kolkata, Mumbai, New Delhi, Sri Jayawardenepura",
  "+05:45": "Kathmandu",
  "+06:00": "Astana, Dhaka",
  "+06:30": "Yangon (Rangoon)",
  "+07:00": "Bangkok, Hanoi, Jakarta",
  "+08:00": "Beijing, Chongqing, Hong Kong, Kuala Lumpur, Singapore, Taipei, Ulaanbaatar, Urumqi",
  "+09:00": "Osaka, Sapporo, Seoul, Tokyo",
  "+10:00": "Canberra, Guam, Melbourne, Port Moresby, Sydney",
  "+11:00": "Solomon Is., New Caledonia",
  "+12:00": "Auckland, Wellington, Fiji",
  "+13:00": "Samoa, Nuk alofa"
}